### ISSUE TITLE
存在乱码的情况

### ISSUE THREAD

**Issue by gobirdwang** [imhuster/Enterprise-Registration-Data-of-Chinese-Mainland#10]
1997年，广东的数据

**Comment by imhuster** [comment]
哪个文件？csv、json 还是 xls ?

**Comment by gobirdwang** [comment]
> 哪个文件？csv、json 还是 xls ?

抱歉没说清楚，1997年的json数据
>\u0000\u0000\u0000深圳市福丰物业管理有限公司

**Comment by imhuster** [comment]
> 
> 
> > 哪个文件？csv、json 还是 xls ?
> 
> 抱歉没说清楚，1997年的json数据
> 
> > \u0000\u0000\u0000深圳市福丰物业管理有限公司

好的，感谢反馈，我处理一下 :-）
