### ISSUE TITLE
此类信息是否涉密，能不能公开？

### ISSUE THREAD

**Issue by heaven0sky** [imhuster/Enterprise-Registration-Data-of-Chinese-Mainland#11]
不管你从哪弄来的，或是从网上收集的，你如果有问题，你要付连带责任的。

**Comment by imhuster** [comment]
感谢提醒，本仓库的声明如下：
本仓库数据的收集行为严格遵守《中华人民共和国网络安全法》及《中华人民共和国刑法》中的相关规定，特此声明以下三点：
1. 本仓库的数据的爬取严格遵守相关政府公开数据网站的“Robots协议”、没有采取任何规避或突破反“爬虫”安防措施的技术手段、没有任何越权的行为；
2. 爬取的数据是公开的、非隐私的、不属于著作权保护范围的信息，数据也仅用于学术目的，本人未从数据中获取任何经济利益；
3. 爬虫的爬取行为未对相关网站的正常运行造成影响。

**Comment by gnaggnoyil** [comment]
保密侠给👴爪巴,丨÷克

**Comment by xn4545945** [comment]
这种信息都能拿出来分享，哪个公司敢录用你呀。况且还在贸易战呢，怕不是个间谍哦。

**Comment by xpxw** [comment]
这个不涉密，工商局公开查询的。

**Comment by bootscript** [comment]
这个还真不涉密，我之前在政府部门工作时处理过工商的涉密数据，详细的是有身份证、任职情况、股份信息等数据，那才是涉密的，因为至少身份证你在天眼上是查不到的，这些都是最基础的数据了。
