### ISSUE TITLE
转载到了一个国内平台，能否加一个链接

### ISSUE THREAD

**Issue by Nihiue** [imhuster/Enterprise-Registration-Data-of-Chinese-Mainland#12]
如题， 这个平台可以直接把数据集用在在线分析上

我会同步这边的更新， 希望这个数据集可以被更多人用到，同时感谢一下作者

https://www.kesci.com/home/dataset/5cf88a45e727f8002c1e1285

**Comment by imhuster** [comment]
可以啊

**Comment by isgbuddy** [comment]
最新下载下来数据目录都是空？@imhuster

**Comment by imhuster** [comment]
> 
> 
> 最新下载下来数据目录都是空？@imhuster

为了下载方便，我已经将相应文件分别保存在 [Enterprise-Registration-Data/csv](https://github.com/imhuster/Enterprise-Registration-Data-of-Chinese-Mainland/tree/csv)、[Enterprise-Registration-Data/xls](https://github.com/imhuster/Enterprise-Registration-Data-of-Chinese-Mainland/tree/xls)、[Enterprise-Registration-Data/json](https://github.com/imhuster/Enterprise-Registration-Data-of-Chinese-Mainland/tree/json) 三个分支中
