### ISSUE TITLE
建议 reset 一下 分支

### ISSUE THREAD

**Issue by Lax** [imhuster/Enterprise-Registration-Data-of-Chinese-Mainland#13]
虽然分成了 3 个 branch，但是 git clone 时默认仍然是包含完整 git 历史的

**Comment by peng0208** [comment]
你需要git clone -b branch

> 虽然分成了 3 个 branch，但是 git clone 时默认仍然是包含完整 git 历史的

**Comment by Lax** [comment]
你试一下再回答，我说的就是 `-b branch`。
当然还可以 `--depth 1`，但是很多应用场景不适用
