### ISSUE TITLE
json/1981/山西.json多了个]

### ISSUE THREAD

**Issue by ChengBinH** [imhuster/Enterprise-Registration-Data-of-Chinese-Mainland#5]
{
        "name": "芮城县大王供销社五交化门市部",
        "code": "91140830MA0GRMTU9K",
        "registrationDay": "1981-07-01",
        "character": "集体分支机构(非法人)",
        "legalRepresentative": "苏革选",
        "capital": "N/A",
        "businessScope": "零售:五金、交电、装璜材料、民用建材、中小农具、日杂。",
        "province": "山西",
        "city": "运城",
        "address": "芮城县大王镇"
    }在这之后多了个] ，用jsonObject读取报错，把]改成，即可

**Comment by imhuster** [comment]
非常感谢反馈，我忘记校验了 -_-

**Comment by ChengBinH** [comment]
> 非常感谢反馈，我忘记校验了 -_-
我也是想试试提取到数据库 哈哈哈
json/1992/浙江.json 该段数据错误
{
        "name": "杭州金马房地产有限公司",
        "code": "91330100609167281F",
        "registrationDay": "1992-10-22",
        "character": "5",
        "legalRepresentative": "000(万美元)",
        "capital": "游乐配套设施(国家禁止或限制的项目除外)的建设经营"
        ","
        businessScope ":"
        程舜梅 ","
        province ":"
        杭州西湖之江旅游度假区 ","
        city ":"
        N / A ","
        address ":"
        杭州 "}, {
            "name": "永康市交通工程有限公司",
            "code": "91330784147461629W",
            "registrationDay": "1992-10-22",
            "character": "N/A",
            "legalRepresentative": "陈军",
            "capital": "2,370.2800(万元人民币)",
            "businessScope": "公路工程施工总承包叁级；公路路面工程专业承包叁级；公路路基工程专业承包叁级；房屋建筑工程施工叁级；土石方工程专业承包叁级（凭有效证件经营）",
            "province": "浙江",
            "city": "金华",
            "address": "浙江省永康市江南街道南苑路83号"
        },

**Comment by imhuster** [comment]
Fixed.

**Comment by ChengBinH** [comment]
thank you
