### ISSUE TITLE
其实只需要CSV文件就可以了

### ISSUE THREAD

**Issue by 0RaymondJiang0** [imhuster/Enterprise-Registration-Data-of-Chinese-Mainland#8]
1，csv文件最小，这样可以极大减小仓库容量。
2，csv转换成其他格式也非常容易，有了csv按理说就不用再提供excel文件了。这两种文件几乎可以互通。
3,  json文件太占用空间了。

**Comment by imhuster** [comment]
> 
> 
> 1，csv文件最小，这样可以极大减小仓库容量。
> 2，csv转换成其他格式也非常容易，有了csv按理说就不用再提供excel文件了。这两种文件几乎可以互通。
> 3, json文件太占用空间了。

嗯，有道理，如果有必要的话，大家可以使用 csv 文件转成其他需要的格式。考虑到方便部分用户使用，可以在 release 版本中提供多种文件格式供大家选择性下载使用。
