### ISSUE TITLE
csv/1999/四川.csv 包含影响解析字符

### ISSUE THREAD

**Issue by micuncang** [imhuster/Enterprise-Registration-Data-of-Chinese-Mainland#9]
![image](https://user-images.githubusercontent.com/3069117/59005172-13f30b80-884f-11e9-8a48-67e4dfab31c1.png)

![image](https://user-images.githubusercontent.com/3069117/59005151-f9209700-884e-11e9-80bd-ccc4272d9b7f.png)

**Comment by imhuster** [comment]
fixed.
